### PR TITLE
Update of Eigen and Pybind11 git submodules

### PR DESCRIPTION
**Pull request by danieleboaretti**
With this PR, the affine_transform package becomes compatible with Python 3.11.

### CODE REVIEW

**Comment by NOhs** [comment]
Thank you for providing this PR. I have to fix some of the broken CI/CD pipelines of this repository and will come back to you, once this is done so that we can push out your changes.

**Comment by NOhs** [comment]
Ok, I fixed the CI/CD pipelines. Can you please:
- Rebase onto master
- Enable Python 3.11 testing (in `test_package.yml` line 9)
- Add Python 3.11 to the `setup.py` line 125

Once the CI/CD runs through and everything is green, we can merge 🙂

**Comment by danieleboaretti** [comment]
I updated the branch and the files as described, it should be good now 😄

**Review by NOhs — APPROVED** [review]

**Comment by NOhs** [comment]
Release 0.3.0 should be out any moment now and should include your fixes. Please open a new issue if you encounter any issues with the release.

**Pull request merged**
